// Used to test timesheets

export default Timesheets = [
  {
    id: 1,
    staffId: 1,
    studentId: 1,
    status: "PENDING",
    date: "25/10/2000", // This should probably be some other format realistically
    startTime: "9:00",
    duration: 60,
  },
  {
    id: 2,
    staffId: 1,
    studentId: 1,
    status: "APPROVED",
    date: "18/10/2000",
    startTime: "18:00",
    duration: 60,
  },
  {
    id: 3,
    staffId: 1,
    studentId: 1,
    status: "DENIED",
    date: "25/10/2000", // This should probably be some other format realistically
    startTime: "9:00",
    duration: 60,
  },
  {
    id: 4,
    staffId: 1,
    studentId: 1,
    status: "APPROVED",
    date: "18/10/2000",
    startTime: "18:00",
    duration: 60,
  },
  {
    id: 5,
    staffId: 1,
    studentId: 1,
    status: "PENDING",
    date: "25/10/2000", // This should probably be some other format realistically
    startTime: "9:00",
    duration: 60,
  },
  {
    id: 6,
    staffId: 1,
    studentId: 1,
    status: "UNKNOWN",
    date: "18/10/2000",
    startTime: "18:00",
    duration: 60,
  },
  {
    id: 7,
    staffId: 1,
    studentId: 1,
    status: "DENIED",
    date: "25/10/2000", // This should probably be some other format realistically
    startTime: "9:00",
    duration: 60,
  },
  {
    id: 8,
    staffId: 1,
    studentId: 1,
    status: "APPROVED",
    date: "18/10/2000",
    startTime: "18:00",
    duration: 60,
  },
  {
    id: 9,
    staffId: 1,
    studentId: 1,
    status: "PENDING",
    date: "25/10/2000", // This should probably be some other format realistically
    startTime: "9:00",
    duration: 60,
  },
  {
    id: 10,
    staffId: 1,
    studentId: 1,
    status: "APPROVED",
    date: "18/10/2000",
    startTime: "18:00",
    duration: 60,
  },
  {
    id: 11,
    staffId: 1,
    studentId: 1,
    status: "DENIED",
    date: "25/10/2000", // This should probably be some other format realistically
    startTime: "9:00",
    duration: 60,
  },
  {
    id: 12,
    staffId: 1,
    studentId: 1,
    status: "APPROVED",
    date: "18/10/2000",
    startTime: "18:00",
    duration: 60,
  },
  {
    id: 13,
    staffId: 1,
    studentId: 1,
    status: "PENDING",
    date: "25/10/2000", // This should probably be some other format realistically
    startTime: "9:00",
    duration: 60,
  },
  {
    id: 14,
    staffId: 1,
    studentId: 1,
    status: "UNKNOWN",
    date: "18/10/2000",
    startTime: "18:00",
    duration: 60,
  },
  {
    id: 15,
    staffId: 1,
    studentId: 1,
    status: "DENIED",
    date: "25/10/2000", // This should probably be some other format realistically
    startTime: "9:00",
    duration: 60,
  },
  {
    id: 16,
    staffId: 1,
    studentId: 1,
    status: "APPROVED",
    date: "18/10/2000",
    startTime: "18:00",
    duration: 60,
  },
]